### ISSUE TITLE
Asset folder missing?

### ISSUE THREAD

**Issue by chadcrowell** [putyourlightson/craft-dump#8]
Hi Ben,

Wondering why I can't see the field to choose the asset source for this Dump install. Latest Craft and Dump on the site. I have an S3 Asset source working and would like to use that for the dumps. Has this been removed or am I missing something?

http://d.pr/i/1ct5g

**Comment by putyourlightson** [comment]
the commit that i believe you're referring to has not been merged with the main branch, but you can find it here:
https://github.com/putyourlightson/craft-dump/pull/5/commits/ef197b85e838037c9a8acb0a71042d27781ac21f

**Comment by chadcrowell** [comment]
Thanks Ben!

**Comment by putyourlightson** [comment]
sure thing
